require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe AntennasController do

  # This should return the minimal set of attributes required to create a valid
  # Antenna. As you add validations to Antenna, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # AntennasController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all antennas as @antennas" do
      antenna = Antenna.create! valid_attributes
      get :index, {}, valid_session
      assigns(:antennas).should eq([antenna])
    end
  end

  describe "GET show" do
    it "assigns the requested antenna as @antenna" do
      antenna = Antenna.create! valid_attributes
      get :show, {:id => antenna.to_param}, valid_session
      assigns(:antenna).should eq(antenna)
    end
  end

  describe "GET new" do
    it "assigns a new antenna as @antenna" do
      get :new, {}, valid_session
      assigns(:antenna).should be_a_new(Antenna)
    end
  end

  describe "GET edit" do
    it "assigns the requested antenna as @antenna" do
      antenna = Antenna.create! valid_attributes
      get :edit, {:id => antenna.to_param}, valid_session
      assigns(:antenna).should eq(antenna)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Antenna" do
        expect {
          post :create, {:antenna => valid_attributes}, valid_session
        }.to change(Antenna, :count).by(1)
      end

      it "assigns a newly created antenna as @antenna" do
        post :create, {:antenna => valid_attributes}, valid_session
        assigns(:antenna).should be_a(Antenna)
        assigns(:antenna).should be_persisted
      end

      it "redirects to the created antenna" do
        post :create, {:antenna => valid_attributes}, valid_session
        response.should redirect_to(Antenna.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved antenna as @antenna" do
        # Trigger the behavior that occurs when invalid params are submitted
        Antenna.any_instance.stub(:save).and_return(false)
        post :create, {:antenna => {}}, valid_session
        assigns(:antenna).should be_a_new(Antenna)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Antenna.any_instance.stub(:save).and_return(false)
        post :create, {:antenna => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested antenna" do
        antenna = Antenna.create! valid_attributes
        # Assuming there are no other antennas in the database, this
        # specifies that the Antenna created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Antenna.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => antenna.to_param, :antenna => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested antenna as @antenna" do
        antenna = Antenna.create! valid_attributes
        put :update, {:id => antenna.to_param, :antenna => valid_attributes}, valid_session
        assigns(:antenna).should eq(antenna)
      end

      it "redirects to the antenna" do
        antenna = Antenna.create! valid_attributes
        put :update, {:id => antenna.to_param, :antenna => valid_attributes}, valid_session
        response.should redirect_to(antenna)
      end
    end

    describe "with invalid params" do
      it "assigns the antenna as @antenna" do
        antenna = Antenna.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Antenna.any_instance.stub(:save).and_return(false)
        put :update, {:id => antenna.to_param, :antenna => {}}, valid_session
        assigns(:antenna).should eq(antenna)
      end

      it "re-renders the 'edit' template" do
        antenna = Antenna.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Antenna.any_instance.stub(:save).and_return(false)
        put :update, {:id => antenna.to_param, :antenna => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested antenna" do
      antenna = Antenna.create! valid_attributes
      expect {
        delete :destroy, {:id => antenna.to_param}, valid_session
      }.to change(Antenna, :count).by(-1)
    end

    it "redirects to the antennas list" do
      antenna = Antenna.create! valid_attributes
      delete :destroy, {:id => antenna.to_param}, valid_session
      response.should redirect_to(antennas_url)
    end
  end

end
