require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe CabinetsController do

  # This should return the minimal set of attributes required to create a valid
  # Cabinet. As you add validations to Cabinet, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # CabinetsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all cabinets as @cabinets" do
      cabinet = Cabinet.create! valid_attributes
      get :index, {}, valid_session
      assigns(:cabinets).should eq([cabinet])
    end
  end

  describe "GET show" do
    it "assigns the requested cabinet as @cabinet" do
      cabinet = Cabinet.create! valid_attributes
      get :show, {:id => cabinet.to_param}, valid_session
      assigns(:cabinet).should eq(cabinet)
    end
  end

  describe "GET new" do
    it "assigns a new cabinet as @cabinet" do
      get :new, {}, valid_session
      assigns(:cabinet).should be_a_new(Cabinet)
    end
  end

  describe "GET edit" do
    it "assigns the requested cabinet as @cabinet" do
      cabinet = Cabinet.create! valid_attributes
      get :edit, {:id => cabinet.to_param}, valid_session
      assigns(:cabinet).should eq(cabinet)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Cabinet" do
        expect {
          post :create, {:cabinet => valid_attributes}, valid_session
        }.to change(Cabinet, :count).by(1)
      end

      it "assigns a newly created cabinet as @cabinet" do
        post :create, {:cabinet => valid_attributes}, valid_session
        assigns(:cabinet).should be_a(Cabinet)
        assigns(:cabinet).should be_persisted
      end

      it "redirects to the created cabinet" do
        post :create, {:cabinet => valid_attributes}, valid_session
        response.should redirect_to(Cabinet.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved cabinet as @cabinet" do
        # Trigger the behavior that occurs when invalid params are submitted
        Cabinet.any_instance.stub(:save).and_return(false)
        post :create, {:cabinet => {}}, valid_session
        assigns(:cabinet).should be_a_new(Cabinet)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Cabinet.any_instance.stub(:save).and_return(false)
        post :create, {:cabinet => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested cabinet" do
        cabinet = Cabinet.create! valid_attributes
        # Assuming there are no other cabinets in the database, this
        # specifies that the Cabinet created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Cabinet.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => cabinet.to_param, :cabinet => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested cabinet as @cabinet" do
        cabinet = Cabinet.create! valid_attributes
        put :update, {:id => cabinet.to_param, :cabinet => valid_attributes}, valid_session
        assigns(:cabinet).should eq(cabinet)
      end

      it "redirects to the cabinet" do
        cabinet = Cabinet.create! valid_attributes
        put :update, {:id => cabinet.to_param, :cabinet => valid_attributes}, valid_session
        response.should redirect_to(cabinet)
      end
    end

    describe "with invalid params" do
      it "assigns the cabinet as @cabinet" do
        cabinet = Cabinet.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Cabinet.any_instance.stub(:save).and_return(false)
        put :update, {:id => cabinet.to_param, :cabinet => {}}, valid_session
        assigns(:cabinet).should eq(cabinet)
      end

      it "re-renders the 'edit' template" do
        cabinet = Cabinet.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Cabinet.any_instance.stub(:save).and_return(false)
        put :update, {:id => cabinet.to_param, :cabinet => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested cabinet" do
      cabinet = Cabinet.create! valid_attributes
      expect {
        delete :destroy, {:id => cabinet.to_param}, valid_session
      }.to change(Cabinet, :count).by(-1)
    end

    it "redirects to the cabinets list" do
      cabinet = Cabinet.create! valid_attributes
      delete :destroy, {:id => cabinet.to_param}, valid_session
      response.should redirect_to(cabinets_url)
    end
  end

end
