require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe PortMapfor3750MesController do

  # This should return the minimal set of attributes required to create a valid
  # PortMapfor3750Me. As you add validations to PortMapfor3750Me, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # PortMapfor3750MesController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all port_mapfor3750_mes as @port_mapfor3750_mes" do
      port_mapfor3750_me = PortMapfor3750Me.create! valid_attributes
      get :index, {}, valid_session
      assigns(:port_mapfor3750_mes).should eq([port_mapfor3750_me])
    end
  end

  describe "GET show" do
    it "assigns the requested port_mapfor3750_me as @port_mapfor3750_me" do
      port_mapfor3750_me = PortMapfor3750Me.create! valid_attributes
      get :show, {:id => port_mapfor3750_me.to_param}, valid_session
      assigns(:port_mapfor3750_me).should eq(port_mapfor3750_me)
    end
  end

  describe "GET new" do
    it "assigns a new port_mapfor3750_me as @port_mapfor3750_me" do
      get :new, {}, valid_session
      assigns(:port_mapfor3750_me).should be_a_new(PortMapfor3750Me)
    end
  end

  describe "GET edit" do
    it "assigns the requested port_mapfor3750_me as @port_mapfor3750_me" do
      port_mapfor3750_me = PortMapfor3750Me.create! valid_attributes
      get :edit, {:id => port_mapfor3750_me.to_param}, valid_session
      assigns(:port_mapfor3750_me).should eq(port_mapfor3750_me)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new PortMapfor3750Me" do
        expect {
          post :create, {:port_mapfor3750_me => valid_attributes}, valid_session
        }.to change(PortMapfor3750Me, :count).by(1)
      end

      it "assigns a newly created port_mapfor3750_me as @port_mapfor3750_me" do
        post :create, {:port_mapfor3750_me => valid_attributes}, valid_session
        assigns(:port_mapfor3750_me).should be_a(PortMapfor3750Me)
        assigns(:port_mapfor3750_me).should be_persisted
      end

      it "redirects to the created port_mapfor3750_me" do
        post :create, {:port_mapfor3750_me => valid_attributes}, valid_session
        response.should redirect_to(PortMapfor3750Me.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved port_mapfor3750_me as @port_mapfor3750_me" do
        # Trigger the behavior that occurs when invalid params are submitted
        PortMapfor3750Me.any_instance.stub(:save).and_return(false)
        post :create, {:port_mapfor3750_me => {}}, valid_session
        assigns(:port_mapfor3750_me).should be_a_new(PortMapfor3750Me)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        PortMapfor3750Me.any_instance.stub(:save).and_return(false)
        post :create, {:port_mapfor3750_me => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested port_mapfor3750_me" do
        port_mapfor3750_me = PortMapfor3750Me.create! valid_attributes
        # Assuming there are no other port_mapfor3750_mes in the database, this
        # specifies that the PortMapfor3750Me created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        PortMapfor3750Me.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => port_mapfor3750_me.to_param, :port_mapfor3750_me => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested port_mapfor3750_me as @port_mapfor3750_me" do
        port_mapfor3750_me = PortMapfor3750Me.create! valid_attributes
        put :update, {:id => port_mapfor3750_me.to_param, :port_mapfor3750_me => valid_attributes}, valid_session
        assigns(:port_mapfor3750_me).should eq(port_mapfor3750_me)
      end

      it "redirects to the port_mapfor3750_me" do
        port_mapfor3750_me = PortMapfor3750Me.create! valid_attributes
        put :update, {:id => port_mapfor3750_me.to_param, :port_mapfor3750_me => valid_attributes}, valid_session
        response.should redirect_to(port_mapfor3750_me)
      end
    end

    describe "with invalid params" do
      it "assigns the port_mapfor3750_me as @port_mapfor3750_me" do
        port_mapfor3750_me = PortMapfor3750Me.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        PortMapfor3750Me.any_instance.stub(:save).and_return(false)
        put :update, {:id => port_mapfor3750_me.to_param, :port_mapfor3750_me => {}}, valid_session
        assigns(:port_mapfor3750_me).should eq(port_mapfor3750_me)
      end

      it "re-renders the 'edit' template" do
        port_mapfor3750_me = PortMapfor3750Me.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        PortMapfor3750Me.any_instance.stub(:save).and_return(false)
        put :update, {:id => port_mapfor3750_me.to_param, :port_mapfor3750_me => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested port_mapfor3750_me" do
      port_mapfor3750_me = PortMapfor3750Me.create! valid_attributes
      expect {
        delete :destroy, {:id => port_mapfor3750_me.to_param}, valid_session
      }.to change(PortMapfor3750Me, :count).by(-1)
    end

    it "redirects to the port_mapfor3750_mes list" do
      port_mapfor3750_me = PortMapfor3750Me.create! valid_attributes
      delete :destroy, {:id => port_mapfor3750_me.to_param}, valid_session
      response.should redirect_to(port_mapfor3750_mes_url)
    end
  end

end
